openapi: 3.0.3
info:
  title: Business process web service gateway API
  description: This document describes REST API of 'Business process web service gateway'
  version: "1.0"
tags:
  - name: bp-webservice-gateway-api
    description: Business process web service gateway Rest API
paths:
  /api/start-bp:
    post:
      tags:
        - bp-webservice-gateway-api
      summary: Start process instance
      description: |-
        ### Endpoint purpose:
         This endpoint allows you to start a business process instance based on the provided _businessProcessDefinitionKey_ in request body.
        ### Business process start validation:
         This endpoint requires valid _businessProcessDefinitionKey_ and _startVariables_. If no business process definition found or required parameters are missing, then _422_ response code returned.
      operationId: startBp
      parameters:
        - name: X-Access-Token
          in: header
          description: Token used for endpoint security
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessProcessStartDataRequest'
            example:
              businessProcessDefinitionKey: my-business-process
              startVariables:
                variable1: value1
                variable2: value2
                variable3: null
        required: true
      responses:
        "200":
          description: Returns result variable of business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessProcessStartResponse'
              example:
                resultVariables:
                  return_var_1: return_value_1
                  return_var_2: null
        "404":
          description: Business process definition not found in allowed inbound process definitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "422":
          description: Business process definition cannot be started or missing required
            start variable for the business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
  /api/start-bp/{key}:
    post:
      tags:
        - bp-webservice-gateway-api
      summary: Start process instance by key
      description: |-
        ### Endpoint purpose:
         This endpoint allows you to start a business process instance by process definition key.
        ### Business process start validation:
         This endpoint requires valid process definition key and _startVariables_. If no business process definition found or required parameters are missing, then _422_ response code returned.
      operationId: startBpByDefinitionKey
      parameters:
        - name: X-Access-Token
          in: header
          description: Token used for endpoint security
          required: true
          schema:
            type: string
        - name: key
          in: path
          description: Process definition key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessProcessStartVariableRequest'
            example:
              startVariables:
                variable1: value1
                variable2: value2
                variable3: null
        required: true
      responses:
        "200":
          description: Returns result variable of business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessProcessStartResponse'
              example:
                resultVariables:
                  return_var_1: return_value_1
                  return_var_2: null
        "404":
          description: Business process definition not found in allowed inbound process definitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "422":
          description: Business process definition cannot be started or missing required
            start variable for the business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
components:
  schemas:
    BusinessProcessStartDataRequest:
      type: object
      properties:
        businessProcessDefinitionKey:
          type: string
        startVariables:
          type: object
          additionalProperties:
            type: object
    BusinessProcessStartResponse:
      type: object
      properties:
        resultVariables:
          type: object
          additionalProperties:
            type: object
    SystemErrorDto:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        message:
          type: string
        messageKey:
          type: string
        messageParameters:
          type: object
          additionalProperties:
            type: string
    BusinessProcessStartVariableRequest:
      type: object
      properties:
        startVariables:
          type: object
          additionalProperties:
            type: object