openapi: 3.0.3
info:
  title: Business processes history service
  description: This document describes REST API of 'Business processes history service'
  version: "1.0"
tags:
- name: process-history-service-api
  description: Business processes history management Rest API
- name: process-history-service-runtime-api
  description: Business processes history management at runtime Rest API
paths:
  /api/runtime/process-instances:
    get:
      tags:
      - process-history-service-runtime-api
      summary: Get a list of historical data of processes in an unfinished state
      description: "### Endpoint assignment: \n This endpoint is used to retrieve\
        \ a list of historical data of processes that are in an incomplete state based\
        \ on specified filtering criteria, including offset, constraint, and sorting\
        \ parameters. Incomplete processes are defined as processes that are currently\
        \ running and have not yet been completed."
      operationId: getProcesses
      parameters:
      - name: X-Access-Token
        in: header
        description: User access token
        schema:
          type: string
      - name: offset
        in: query
        description: Record offset
        required: true
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Maximum number of records to return
        required: true
        schema:
          type: integer
          default: 10
      - name: sort
        in: query
        description: "Field and order for sorting the records. Example: asc(<field>)\
          \ / desc(<field>)"
        required: true
        schema:
          type: string
          default: desc(endTime)
      - name: securityContext
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SecurityContext'
      responses:
        "200":
          description: OK. List of historical process data successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessResponse'
              example:
              - processInstanceId: "1234"
                superProcessInstanceId: "5678"
                processDefinitionId: "91011"
                processDefinitionKey: myProcess
                processDefinitionName: My Process
                businessKey: 1234-5678
                startTime: 2021-01-01T00:00:00Z
                startUserId: john.doe
                status:
                  code: InProgress
                  title: In Progress
        "400":
          description: Bad Request. Invalid excerpt type or incorrect request parameters.
          content:
            application/json: {}
        "401":
          description: Unauthorized. Missing or invalid access token or digital signature.
          content:
            application/json: {}
        "500":
          description: Internal Server Error. Server error while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /api/runtime/process-instances/count:
    get:
      tags:
      - process-history-service-runtime-api
      summary: Get the count of unfinished process instances
      description: Returns a count of unfinished process instances based on specified
        filtering criteria. Unfinished processes refer to those processes that are
        currently executing and have not yet completed.
      operationId: count
      parameters:
      - name: X-Access-Token
        in: header
        description: User access token
        schema:
          type: string
      - name: securityContext
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SecurityContext'
      responses:
        "200":
          description: OK. Count of unfinished process instances successfully retrieved.
          content:
            application/json:
              schema:
                type: integer
              example:
                count: 10
        "400":
          description: Bad Request. Invalid request parameters.
          content:
            application/json: {}
        "401":
          description: Unauthorized. Missing or invalid access token or digital signature.
          content:
            application/json: {}
        "500":
          description: Internal Server Error. Server error while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /api/history/tasks:
    get:
      tags:
      - process-history-service-api
      summary: Get a list of historical data of tasks
      description: "### Endpoint assignment: \n This endpoint is used to retrieve\
        \ a list of historical data of tasks based on specified filtering criteria,\
        \ including offset, constraint, and sorting parameters."
      operationId: getTasks
      parameters:
      - name: X-Access-Token
        in: header
        description: User access token
        schema:
          type: string
      - name: offset
        in: query
        description: Record offset
        required: true
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Maximum number of records to return
        required: true
        schema:
          type: integer
          default: 10
      - name: sort
        in: query
        description: "Field and order for sorting the records. Example: asc(<field>)\
          \ / desc(<field>)"
        required: true
        schema:
          type: string
          default: desc(endTime)
      - name: securityContext
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SecurityContext'
      responses:
        "200":
          description: OK. List of historical tasks data successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessResponse'
              example:
              - activityInstanceId: "10001"
                taskDefinitionKey: task1
                taskDefinitionName: First task
                processInstanceId: "1234"
                processDefinitionId: "91011"
                processDefinitionKey: myProcess
                processDefinitionName: My Process
                startTime: 2021-04-01T09:00:00Z
                endTime: 2021-04-01T12:00:00Z
                assignee: john.doe
        "400":
          description: Bad Request. Invalid excerpt type or incorrect request parameters.
          content:
            application/json: {}
        "401":
          description: Unauthorized. Missing or invalid access token or digital signature.
          content:
            application/json: {}
        "500":
          description: Internal Server Error. Server error while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /api/history/process-instances:
    get:
      tags:
      - process-history-service-api
      summary: Get a list of historical data of processes
      description: "### Endpoint assignment: \n This endpoint is used to retrieve\
        \ a list of historical data of processes based on specified filtering criteria,\
        \ including offset, constraint, and sorting parameters."
      operationId: getProcesses_1
      parameters:
      - name: X-Access-Token
        in: header
        description: User access token
        schema:
          type: string
      - name: offset
        in: query
        description: Record offset
        required: true
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Maximum number of records to return
        required: true
        schema:
          type: integer
          default: 10
      - name: sort
        in: query
        description: "Field and order for sorting the records. Example: asc(<field>)\
          \ / desc(<field>)"
        required: true
        schema:
          type: string
          default: desc(endTime)
      - name: securityContext
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SecurityContext'
      responses:
        "200":
          description: OK. List of historical process data successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessResponse'
              example:
              - processInstanceId: "1234"
                superProcessInstanceId: "5678"
                processDefinitionId: "91011"
                processDefinitionKey: myProcess
                processDefinitionName: My Process
                businessKey: 1234-5678
                startTime: 2021-01-01T00:00:00Z
                endTime: 2021-01-01T00:01:00Z
                startUserId: john.doe
                excerptId: "4321"
                status:
                  code: COMPLETED
                  title: COMPLETED
        "400":
          description: Bad Request. Invalid excerpt type or incorrect request parameters.
          content:
            application/json: {}
        "401":
          description: Unauthorized. Missing or invalid access token or digital signature.
          content:
            application/json: {}
        "500":
          description: Internal Server Error. Server error while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
components:
  schemas:
    ProcessResponse:
      type: object
      properties:
        processInstanceId:
          type: string
        superProcessInstanceId:
          type: string
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type: string
        businessKey:
          type: string
        startTime:
          type: string
          format: date-time
        startUserId:
          type: string
        status:
          $ref: '#/components/schemas/StatusModel'
    StatusModel:
      type: object
      properties:
        code:
          type: string
          enum:
          - ACTIVE
          - PENDING
          - SUSPENDED
          - COMPLETED
          - EXTERNALLY_TERMINATED
        title:
          type: string
    DetailedErrorResponse:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        details:
          type: object
    SecurityContext:
      type: object
      properties:
        accessToken:
          type: string
        digitalSignature:
          type: string
        digitalSignatureDerived:
          type: string
        digitalSignatureChecksum:
          type: string
        digitalSignatureDerivedChecksum:
          type: string
